AUTHOR_NAME="Jérémie DECOCK"
AUTHOR_EMAIL="jd.jdhp@gmail.com"
AUTHOR_WEB_SITE="www.jdhp.org"

COPYRIGHT_NOTICE="Copyright (c) 2016,2017 ${AUTHOR_NAME} (${AUTHOR_WEB_SITE})"

DOCUMENT_DATE="4 Janvier 2017"
INSTITUTE=""
DOCUMENT_SUBJECT="glossaire de physique"
DOCUMENT_KEYWORDS="physique,astrophysique,physique des particules"

DOCUMENT_TITLE="Glossaire d'astrophysique et de physique des particules"
DOCUMENT_SUBTITLE=""
DOCUMENT_FILE_BASE_NAME="physics_glossary_fr"

DOCUMENT_GIT_FORGE_ACCOUNT="jdhp-docs"
DOCUMENT_GIT_FORGE_REPOSITORY_NAME="physics-glossary"

DOCUMENT_GIT_FORGE_DOMAIN="github.com"
DOCUMENT_GIT_FORGE_URL="https://${DOCUMENT_GIT_FORGE_DOMAIN}"
DOCUMENT_GIT_FORGE_PROJECT_URL="${DOCUMENT_GIT_FORGE_URL}/${DOCUMENT_GIT_FORGE_ACCOUNT}/${DOCUMENT_GIT_FORGE_REPOSITORY_NAME}"
DOCUMENT_ISSUE_TRACKER_URL="${DOCUMENT_GIT_FORGE_URL}/${DOCUMENT_GIT_FORGE_ACCOUNT}/${DOCUMENT_GIT_FORGE_REPOSITORY_NAME}/issues"

DOCUMENT_WEB_SITE_URL="http://www.jdhp.org/documentation_fr.html#${DOCUMENT_FILE_BASE_NAME}"
DOCUMENT_HTML_URL="http://www.jdhp.org/docs/${DOCUMENT_FILE_BASE_NAME}/${DOCUMENT_FILE_BASE_NAME}.html"
DOCUMENT_PDF_URL="http://www.jdhp.org/dl/pdf/${DOCUMENT_FILE_BASE_NAME}.pdf"

HTML_TMP_DIR="html_tmp"
